// Code generated by "stringer -linecomment -type valueCode -output /mnt/e/projects/books/fb2converter_kfx/processor/kfx/ionvalue_enums_string.go /mnt/e/projects/books/fb2converter_kfx/processor/kfx/ionvalue.go"; DO NOT EDIT.

package kfx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[vcNull-0]
	_ = x[vcBool-1]
	_ = x[vcPInt-2]
	_ = x[vcNInt-3]
	_ = x[vcFloat-4]
	_ = x[vcDecimal-5]
	_ = x[vcTimestamp-6]
	_ = x[vcSymbol-7]
	_ = x[vcString-8]
	_ = x[vcCLOB-9]
	_ = x[vcBLOB-10]
	_ = x[vcList-11]
	_ = x[vcSExp-12]
	_ = x[vcStruct-13]
	_ = x[vcAnnotation-14]
	_ = x[vcReserved-15]
}

const _valueCode_name = "nullboolintintfloatdecimaltimestampsymbolstringclobbloblistsexpstructannotationreserved"

var _valueCode_index = [...]uint8{0, 4, 8, 11, 14, 19, 26, 35, 41, 47, 51, 55, 59, 63, 69, 79, 87}

func (i valueCode) String() string {
	if i >= valueCode(len(_valueCode_index)-1) {
		return "valueCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _valueCode_name[_valueCode_index[i]:_valueCode_index[i+1]]
}
