// Code generated by "stringer -linecomment -type KDFTable -output /mnt/e/projects/books/fb2converter_kfx/processor/kfx/sqltable_enums_string.go /mnt/e/projects/books/fb2converter_kfx/processor/kfx/sqltable.go"; DO NOT EDIT.

package kfx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TableSchema-0]
	_ = x[TableKFXID-1]
	_ = x[TableFragmentProps-2]
	_ = x[TableFragments-3]
	_ = x[TableCapabilities-4]
	_ = x[TableIndexInfo-5]
	_ = x[TableGCFragmentProps-6]
	_ = x[TableGCReachable-7]
	_ = x[UnsupportedKDFTable-8]
}

const _KDFTable_name = "sqlite_masterkfxid_translationfragment_propertiesfragmentscapabilitiesindex_infogc_fragment_propertiesgc_reachable"

var _KDFTable_index = [...]uint8{0, 13, 30, 49, 58, 70, 80, 102, 114, 114}

func (i KDFTable) String() string {
	if i < 0 || i >= KDFTable(len(_KDFTable_index)-1) {
		return "KDFTable(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KDFTable_name[_KDFTable_index[i]:_KDFTable_index[i+1]]
}
